# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gameofChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gameofChat
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Firebase/Analytics'
	pod 'DropDown'
	pod 'FontAwesome.swift'
	pod 'Segmentio'



  target 'gameofChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gameofChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
